import { enCA, enUS, frCA } from "./routing"

export const miscellaneousStrings = {
    [enCA]: {
        dlAppstore: "Download the app in the Apple AppStore",
        dlPlaystore: "Download the app in the Google Playstore",
        downloadTheApp: "Download the App!",
        quoteNow: "Quote Now",
        companyName: "Goose",
    },
    [enUS]: {
        dlAppstore: "Download the app in the Apple AppStore",
        dlPlaystore: "Download the app in the Google Playstore",
        downloadTheApp: "Download the App!",
        quoteNow: "Quote Now",
        companyName: "SmartBunny",
    },
    [frCA]: {
        dlAppstore: "Téléchargez l'application sur l'App Store d'Apple.",
        dlPlaystore: "Téléchargez l'application sur le Google Play Store.",
        downloadTheApp: "Téléchargez l'application!",
        quoteNow: "Soumission",
        companyName: "Goose",
    },
} as const

export const stateMappings = {
    AL: 'Alabama',
    AK: 'Alaska',
    AZ: 'Arizona',
    AR: 'Arkansas',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DC: 'District of Columbia',
    DE: 'Delaware',
    FL: 'Florida',
    GA: 'Georgia',
    HI: 'Hawaii',
    ID: 'Idaho',
    IL: 'Illinois',
    IN: 'Indiana',
    IA: 'Iowa',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    ME: 'Maine',
    MD: 'Maryland',
    MA: 'Massachusetts',
    MI: 'Michigan',
    MN: 'Minnesota',
    MS: 'Mississippi',
    MO: 'Missouri',
    MT: 'Montana',
    NE: 'Nebraska',
    NV: 'Nevada',
    NH: 'New Hampshire',
    NJ: 'New Jersey',
    NM: 'New Mexico',
    NY: 'New York',
    NC: 'North Carolina',
    ND: 'North Dakota',
    OH: 'Ohio',
    OK: 'Oklahoma',
    OR: 'Oregon',
    PA: 'Pennsylvania',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VT: 'Vermont',
    VA: 'Virginia',
    WA: 'Washington',
    WV: 'West Virginia',
    WI: 'Wisconsin',
    WY: 'Wyoming'
};